modLoader = "javafml"
loaderVersion = "[62,)"

license = "${project_license}"
issueTrackerURL = "${issues_tracker_url}"
showAsResourcePack = false

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    displayURL = "${website_url}"
    logoFile = "assets/${mod_id}/icon_64.png"
    credits = "Everyone who contributed on Crowdin and GitHub."
    authors = "${mod_author}"
    updateJSONURL = "${source_url}/raw/refs/heads/${minecraft_version}/.github/forge-update.json"
    description = '''
${mod_description}
In loving memory of §d${ng_name}§f.
'''

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "[${forge_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${minecraft_version},)"
    ordering = "NONE"
    side = "BOTH"
