package net.seface.somemoreblocks.registry;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;
import net.seface.somemoreblocks.MoreBlocks;
import net.seface.somemoreblocks.item.LeavesBucketItem;
import net.seface.somemoreblocks.utils.MBUtils;

public class MBCreativeTabs {
  public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, MoreBlocks.ID);

  private static final RegistryObject<CreativeModeTab> MORE_BUILDING_BLOCKS = CREATIVE_MODE_TABS.register("more_building_blocks", () -> CreativeModeTab.builder(CreativeModeTab.Row.TOP, 0)
    .icon(() -> MBBlocks.MOSSY_BRICKS.get().asItem().getDefaultInstance())
    .title(Component.translatable("itemGroup.somemoreblocks.buildingBlocks"))
    .displayItems((ctx, entry) -> {

      entry.accept(MBBlocks.CARVED_OAK_LOG.get());
      entry.accept(MBBlocks.CARVED_OAK_WOOD.get());
      entry.accept(MBBlocks.OAK_MOSAIC.get());
      entry.accept(MBBlocks.OAK_MOSAIC_STAIRS.get());
      entry.accept(MBBlocks.OAK_MOSAIC_SLAB.get());
      entry.accept(MBBlocks.CARVED_SPRUCE_LOG.get());
      entry.accept(MBBlocks.CARVED_SPRUCE_WOOD.get());
      entry.accept(MBBlocks.SPRUCE_MOSAIC.get());
      entry.accept(MBBlocks.SPRUCE_MOSAIC_STAIRS.get());
      entry.accept(MBBlocks.SPRUCE_MOSAIC_SLAB.get());
      entry.accept(MBBlocks.CARVED_BIRCH_LOG.get());
      entry.accept(MBBlocks.CARVED_BIRCH_WOOD.get());
      entry.accept(MBBlocks.BIRCH_MOSAIC.get());
      entry.accept(MBBlocks.BIRCH_MOSAIC_STAIRS.get());
      entry.accept(MBBlocks.BIRCH_MOSAIC_SLAB.get());
      entry.accept(MBBlocks.CARVED_JUNGLE_LOG.get());
      entry.accept(MBBlocks.CARVED_JUNGLE_WOOD.get());
      entry.accept(MBBlocks.JUNGLE_MOSAIC.get());
      entry.accept(MBBlocks.JUNGLE_MOSAIC_STAIRS.get());
      entry.accept(MBBlocks.JUNGLE_MOSAIC_SLAB.get());
      entry.accept(MBBlocks.CARVED_ACACIA_LOG.get());
      entry.accept(MBBlocks.CARVED_ACACIA_WOOD.get());
      entry.accept(MBBlocks.ACACIA_MOSAIC.get());
      entry.accept(MBBlocks.ACACIA_MOSAIC_STAIRS.get());
      entry.accept(MBBlocks.ACACIA_MOSAIC_SLAB.get());
      entry.accept(MBBlocks.CARVED_DARK_OAK_LOG.get());
      entry.accept(MBBlocks.CARVED_DARK_OAK_WOOD.get());
      entry.accept(MBBlocks.DARK_OAK_MOSAIC.get());
      entry.accept(MBBlocks.DARK_OAK_MOSAIC_STAIRS.get());
      entry.accept(MBBlocks.DARK_OAK_MOSAIC_SLAB.get());
      entry.accept(MBBlocks.CARVED_MANGROVE_LOG.get());
      entry.accept(MBBlocks.CARVED_MANGROVE_WOOD.get());
      entry.accept(MBBlocks.MANGROVE_MOSAIC.get());
      entry.accept(MBBlocks.MANGROVE_MOSAIC_STAIRS.get());
      entry.accept(MBBlocks.MANGROVE_MOSAIC_SLAB.get());
      entry.accept(MBBlocks.CARVED_CRIMSON_STEM.get());
      entry.accept(MBBlocks.CARVED_CRIMSON_HYPHAE.get());
      entry.accept(MBBlocks.CRIMSON_MOSAIC.get());
      entry.accept(MBBlocks.CRIMSON_MOSAIC_STAIRS.get());
      entry.accept(MBBlocks.CRIMSON_MOSAIC_SLAB.get());
      entry.accept(MBBlocks.CARVED_WARPED_STEM.get());
      entry.accept(MBBlocks.CARVED_WARPED_HYPHAE.get());
      entry.accept(MBBlocks.WARPED_MOSAIC.get());
      entry.accept(MBBlocks.WARPED_MOSAIC_STAIRS.get());
      entry.accept(MBBlocks.WARPED_MOSAIC_SLAB.get());
      entry.accept(MBBlocks.CARVED_CHERRY_LOG.get());
      entry.accept(MBBlocks.CARVED_CHERRY_WOOD.get());
      entry.accept(MBBlocks.CHERRY_MOSAIC.get());
      entry.accept(MBBlocks.CHERRY_MOSAIC_STAIRS.get());
      entry.accept(MBBlocks.CHERRY_MOSAIC_SLAB.get());
      entry.accept(MBBlocks.CARVED_BAMBOO_BLOCK.get());
      entry.accept(MBBlocks.POLISHED_STONE.get());
      entry.accept(MBBlocks.POLISHED_STONE_STAIRS.get());
      entry.accept(MBBlocks.POLISHED_STONE_SLAB.get());
      entry.accept(MBBlocks.STONE_PILLAR.get());
      entry.accept(MBBlocks.STONE_TILES.get());
      entry.accept(MBBlocks.CRACKED_STONE_TILES.get());
      entry.accept(MBBlocks.STONE_TILE_STAIRS.get());
      entry.accept(MBBlocks.STONE_TILE_SLAB.get());
      entry.accept(MBBlocks.STONE_TILE_WALL.get());
      entry.accept(MBBlocks.CHISELED_GRANITE_BRICKS.get());
      entry.accept(MBBlocks.GRANITE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_GRANITE_BRICKS.get());
      entry.accept(MBBlocks.GRANITE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.GRANITE_BRICK_SLAB.get());
      entry.accept(MBBlocks.GRANITE_BRICK_WALL.get());
      entry.accept(MBBlocks.GRANITE_PILLAR.get());
      entry.accept(MBBlocks.GRANITE_TILES.get());
      entry.accept(MBBlocks.CRACKED_GRANITE_TILES.get());
      entry.accept(MBBlocks.GRANITE_TILE_STAIRS.get());
      entry.accept(MBBlocks.GRANITE_TILE_SLAB.get());
      entry.accept(MBBlocks.GRANITE_TILE_WALL.get());
      entry.accept(MBBlocks.MOSSY_GRANITE_BRICKS.get());
      entry.accept(MBBlocks.MOSSY_GRANITE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.MOSSY_GRANITE_BRICK_SLAB.get());
      entry.accept(MBBlocks.MOSSY_GRANITE_BRICK_WALL.get());
      entry.accept(MBBlocks.SMOOTH_GRANITE.get());
      entry.accept(MBBlocks.SMOOTH_GRANITE_SLAB.get());
      entry.accept(MBBlocks.CHISELED_DIORITE_BRICKS.get());
      entry.accept(MBBlocks.DIORITE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_DIORITE_BRICKS.get());
      entry.accept(MBBlocks.DIORITE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.DIORITE_BRICK_SLAB.get());
      entry.accept(MBBlocks.DIORITE_BRICK_WALL.get());
      entry.accept(MBBlocks.DIORITE_PILLAR.get());
      entry.accept(MBBlocks.DIORITE_TILES.get());
      entry.accept(MBBlocks.CRACKED_DIORITE_TILES.get());
      entry.accept(MBBlocks.DIORITE_TILE_STAIRS.get());
      entry.accept(MBBlocks.DIORITE_TILE_SLAB.get());
      entry.accept(MBBlocks.DIORITE_TILE_WALL.get());
      entry.accept(MBBlocks.MOSSY_DIORITE_BRICKS.get());
      entry.accept(MBBlocks.MOSSY_DIORITE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.MOSSY_DIORITE_BRICK_SLAB.get());
      entry.accept(MBBlocks.MOSSY_DIORITE_BRICK_WALL.get());
      entry.accept(MBBlocks.SMOOTH_DIORITE.get());
      entry.accept(MBBlocks.SMOOTH_DIORITE_SLAB.get());
      entry.accept(MBBlocks.CHISELED_ANDESITE_BRICKS.get());
      entry.accept(MBBlocks.ANDESITE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_ANDESITE_BRICKS.get());
      entry.accept(MBBlocks.ANDESITE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.ANDESITE_BRICK_SLAB.get());
      entry.accept(MBBlocks.ANDESITE_BRICK_WALL.get());
      entry.accept(MBBlocks.ANDESITE_PILLAR.get());
      entry.accept(MBBlocks.ANDESITE_TILES.get());
      entry.accept(MBBlocks.CRACKED_ANDESITE_TILES.get());
      entry.accept(MBBlocks.ANDESITE_TILE_STAIRS.get());
      entry.accept(MBBlocks.ANDESITE_TILE_SLAB.get());
      entry.accept(MBBlocks.ANDESITE_TILE_WALL.get());
      entry.accept(MBBlocks.MOSSY_ANDESITE_BRICKS.get());
      entry.accept(MBBlocks.MOSSY_ANDESITE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.MOSSY_ANDESITE_BRICK_SLAB.get());
      entry.accept(MBBlocks.MOSSY_ANDESITE_BRICK_WALL.get());
      entry.accept(MBBlocks.SMOOTH_ANDESITE.get());
      entry.accept(MBBlocks.SMOOTH_ANDESITE_SLAB.get());
      entry.accept(MBBlocks.DEEPSLATE_PILLAR.get());
      entry.accept(MBBlocks.POLISHED_CALCITE.get());
      entry.accept(MBBlocks.POLISHED_CALCITE_STAIRS.get());
      entry.accept(MBBlocks.POLISHED_CALCITE_SLAB.get());
      entry.accept(MBBlocks.CHISELED_CALCITE_BRICKS.get());
      entry.accept(MBBlocks.CALCITE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_CALCITE_BRICKS.get());
      entry.accept(MBBlocks.CALCITE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.CALCITE_BRICK_SLAB.get());
      entry.accept(MBBlocks.CALCITE_BRICK_WALL.get());
      entry.accept(MBBlocks.CALCITE_PILLAR.get());
      entry.accept(MBBlocks.CALCITE_TILES.get());
      entry.accept(MBBlocks.CRACKED_CALCITE_TILES.get());
      entry.accept(MBBlocks.CALCITE_TILE_STAIRS.get());
      entry.accept(MBBlocks.CALCITE_TILE_SLAB.get());
      entry.accept(MBBlocks.CALCITE_TILE_WALL.get());
      entry.accept(MBBlocks.MOSSY_CALCITE_BRICKS.get());
      entry.accept(MBBlocks.MOSSY_CALCITE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.MOSSY_CALCITE_BRICK_SLAB.get());
      entry.accept(MBBlocks.MOSSY_CALCITE_BRICK_WALL.get());
      entry.accept(MBBlocks.SMOOTH_CALCITE.get());
      entry.accept(MBBlocks.SMOOTH_CALCITE_SLAB.get());
      MBUtils.entryWithoutFeatureFlag(ctx, entry, FeatureFlags.UPDATE_1_21, MBBlocks.TUFF_BRICKS.get().asItem());
      entry.accept(MBBlocks.CRACKED_TUFF_BRICKS.get());
      MBUtils.entryWithoutFeatureFlag(ctx, entry, FeatureFlags.UPDATE_1_21, MBBlocks.TUFF_BRICK_SLAB.get().asItem());
      MBUtils.entryWithoutFeatureFlag(ctx, entry, FeatureFlags.UPDATE_1_21, MBBlocks.TUFF_BRICK_STAIRS.get().asItem());
      MBUtils.entryWithoutFeatureFlag(ctx, entry, FeatureFlags.UPDATE_1_21, MBBlocks.TUFF_BRICK_WALL.get().asItem());
      MBUtils.entryWithoutFeatureFlag(ctx, entry, FeatureFlags.UPDATE_1_21, MBBlocks.CHISELED_TUFF_BRICKS.get().asItem());
      MBUtils.entryWithoutFeatureFlag(ctx, entry, FeatureFlags.UPDATE_1_21, MBBlocks.POLISHED_TUFF.get().asItem());
      MBUtils.entryWithoutFeatureFlag(ctx, entry, FeatureFlags.UPDATE_1_21, MBBlocks.POLISHED_TUFF_SLAB.get().asItem());
      MBUtils.entryWithoutFeatureFlag(ctx, entry, FeatureFlags.UPDATE_1_21, MBBlocks.POLISHED_TUFF_STAIRS.get().asItem());
      entry.accept(MBBlocks.TUFF_PILLAR.get());
      entry.accept(MBBlocks.TUFF_TILES.get());
      entry.accept(MBBlocks.CRACKED_TUFF_TILES.get());
      entry.accept(MBBlocks.TUFF_TILE_STAIRS.get());
      entry.accept(MBBlocks.TUFF_TILE_SLAB.get());
      entry.accept(MBBlocks.TUFF_TILE_WALL.get());
      entry.accept(MBBlocks.MOSSY_TUFF_BRICKS.get());
      entry.accept(MBBlocks.MOSSY_TUFF_BRICK_STAIRS.get());
      entry.accept(MBBlocks.MOSSY_TUFF_BRICK_SLAB.get());
      entry.accept(MBBlocks.MOSSY_TUFF_BRICK_WALL.get());
      entry.accept(MBBlocks.SMOOTH_TUFF.get());
      entry.accept(MBBlocks.SMOOTH_TUFF_SLAB.get());
      entry.accept(MBBlocks.POLISHED_DRIPSTONE.get());
      entry.accept(MBBlocks.POLISHED_DRIPSTONE_STAIRS.get());
      entry.accept(MBBlocks.POLISHED_DRIPSTONE_SLAB.get());
      entry.accept(MBBlocks.CHISELED_DRIPSTONE_BRICKS.get());
      entry.accept(MBBlocks.DRIPSTONE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_DRIPSTONE_BRICKS.get());
      entry.accept(MBBlocks.DRIPSTONE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.DRIPSTONE_BRICK_SLAB.get());
      entry.accept(MBBlocks.DRIPSTONE_BRICK_WALL.get());
      entry.accept(MBBlocks.DRIPSTONE_PILLAR.get());
      entry.accept(MBBlocks.DRIPSTONE_TILES.get());
      entry.accept(MBBlocks.CRACKED_DRIPSTONE_TILES.get());
      entry.accept(MBBlocks.DRIPSTONE_TILE_STAIRS.get());
      entry.accept(MBBlocks.DRIPSTONE_TILE_SLAB.get());
      entry.accept(MBBlocks.DRIPSTONE_TILE_WALL.get());
      entry.accept(MBBlocks.MOSSY_DRIPSTONE_BRICKS.get());
      entry.accept(MBBlocks.MOSSY_DRIPSTONE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.MOSSY_DRIPSTONE_BRICK_SLAB.get());
      entry.accept(MBBlocks.MOSSY_DRIPSTONE_BRICK_WALL.get());
      entry.accept(MBBlocks.SMOOTH_DRIPSTONE.get());
      entry.accept(MBBlocks.SMOOTH_DRIPSTONE_SLAB.get());
      entry.accept(MBBlocks.CRACKED_BRICKS_BLOCK.get());
      entry.accept(MBBlocks.MOSSY_BRICKS.get());
      entry.accept(MBBlocks.MOSSY_BRICK_STAIRS.get());
      entry.accept(MBBlocks.MOSSY_BRICK_SLAB.get());
      entry.accept(MBBlocks.MOSSY_BRICK_WALL.get());
      entry.accept(MBBlocks.POLISHED_MUD.get());
      entry.accept(MBBlocks.POLISHED_MUD_STAIRS.get());
      entry.accept(MBBlocks.POLISHED_MUD_SLAB.get());
      entry.accept(MBBlocks.CHISELED_MUD_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_MUD_BRICKS.get());
      entry.accept(MBBlocks.MUD_PILLAR.get());
      entry.accept(MBBlocks.MUD_TILES.get());
      entry.accept(MBBlocks.CRACKED_MUD_TILES.get());
      entry.accept(MBBlocks.MUD_TILE_STAIRS.get());
      entry.accept(MBBlocks.MUD_TILE_SLAB.get());
      entry.accept(MBBlocks.MUD_TILE_WALL.get());
      entry.accept(MBBlocks.MOSSY_MUD_BRICKS.get());
      entry.accept(MBBlocks.MOSSY_MUD_BRICK_STAIRS.get());
      entry.accept(MBBlocks.MOSSY_MUD_BRICK_SLAB.get());
      entry.accept(MBBlocks.MOSSY_MUD_BRICK_WALL.get());
      entry.accept(MBBlocks.SMOOTH_MUD.get());
      entry.accept(MBBlocks.SMOOTH_MUD_SLAB.get());
      entry.accept(MBBlocks.SANDSTONE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_SANDSTONE_BRICKS.get());
      entry.accept(MBBlocks.SANDSTONE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.SANDSTONE_BRICK_SLAB.get());
      entry.accept(MBBlocks.SANDSTONE_BRICK_WALL.get());
      entry.accept(MBBlocks.SANDSTONE_PILLAR.get());
      entry.accept(MBBlocks.SANDSTONE_TILES.get());
      entry.accept(MBBlocks.CRACKED_SANDSTONE_TILES.get());
      entry.accept(MBBlocks.SANDSTONE_TILE_STAIRS.get());
      entry.accept(MBBlocks.SANDSTONE_TILE_SLAB.get());
      entry.accept(MBBlocks.SANDSTONE_TILE_WALL.get());
      entry.accept(MBBlocks.MOSSY_SANDSTONE_BRICKS.get());
      entry.accept(MBBlocks.MOSSY_SANDSTONE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.MOSSY_SANDSTONE_BRICK_SLAB.get());
      entry.accept(MBBlocks.MOSSY_SANDSTONE_BRICK_WALL.get());
      entry.accept(MBBlocks.RED_SANDSTONE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_RED_SANDSTONE_BRICKS.get());
      entry.accept(MBBlocks.RED_SANDSTONE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.RED_SANDSTONE_BRICK_SLAB.get());
      entry.accept(MBBlocks.RED_SANDSTONE_BRICK_WALL.get());
      entry.accept(MBBlocks.RED_SANDSTONE_PILLAR.get());
      entry.accept(MBBlocks.RED_SANDSTONE_TILES.get());
      entry.accept(MBBlocks.CRACKED_RED_SANDSTONE_TILES.get());
      entry.accept(MBBlocks.RED_SANDSTONE_TILE_STAIRS.get());
      entry.accept(MBBlocks.RED_SANDSTONE_TILE_SLAB.get());
      entry.accept(MBBlocks.RED_SANDSTONE_TILE_WALL.get());
      entry.accept(MBBlocks.MOSSY_RED_SANDSTONE_BRICKS.get());
      entry.accept(MBBlocks.MOSSY_RED_SANDSTONE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.MOSSY_RED_SANDSTONE_BRICK_SLAB.get());
      entry.accept(MBBlocks.MOSSY_RED_SANDSTONE_BRICK_WALL.get());
      entry.accept(MBBlocks.POLISHED_PRISMARINE.get());
      entry.accept(MBBlocks.POLISHED_PRISMARINE_STAIRS.get());
      entry.accept(MBBlocks.POLISHED_PRISMARINE_SLAB.get());
      entry.accept(MBBlocks.CHISELED_PRISMARINE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_PRISMARINE_BRICKS.get());
      entry.accept(MBBlocks.PRISMARINE_PILLAR.get());
      entry.accept(MBBlocks.PRISMARINE_TILES.get());
      entry.accept(MBBlocks.CRACKED_PRISMARINE_TILES.get());
      entry.accept(MBBlocks.PRISMARINE_TILE_STAIRS.get());
      entry.accept(MBBlocks.PRISMARINE_TILE_SLAB.get());
      entry.accept(MBBlocks.PRISMARINE_TILE_WALL.get());
      entry.accept(MBBlocks.MOSSY_PRISMARINE_BRICKS.get());
      entry.accept(MBBlocks.MOSSY_PRISMARINE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.MOSSY_PRISMARINE_BRICK_SLAB.get());
      entry.accept(MBBlocks.MOSSY_PRISMARINE_BRICK_WALL.get());
      entry.accept(MBBlocks.SMOOTH_PRISMARINE.get());
      entry.accept(MBBlocks.SMOOTH_PRISMARINE_SLAB.get());
      entry.accept(MBBlocks.NETHER_BRICKS_PILLAR.get());
      entry.accept(MBBlocks.CRACKED_RED_NETHER_BRICKS.get());
      entry.accept(MBBlocks.CHISELED_RED_NETHER_BRICKS.get());
      entry.accept(MBBlocks.RED_NETHER_BRICKS_PILLAR.get());
      entry.accept(MBBlocks.POLISHED_BLACKSTONE_PILLAR.get());
      entry.accept(MBBlocks.POLISHED_BLACKSTONE_TILES.get());
      entry.accept(MBBlocks.CRACKED_POLISHED_BLACKSTONE_TILES.get());
      entry.accept(MBBlocks.POLISHED_BLACKSTONE_TILE_STAIRS.get());
      entry.accept(MBBlocks.POLISHED_BLACKSTONE_TILE_SLAB.get());
      entry.accept(MBBlocks.POLISHED_BLACKSTONE_TILE_WALL.get());
      entry.accept(MBBlocks.CORRUPTED_POLISHED_BLACKSTONE_BRICKS.get());
      entry.accept(MBBlocks.CORRUPTED_POLISHED_BLACKSTONE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.CORRUPTED_POLISHED_BLACKSTONE_BRICK_SLAB.get());
      entry.accept(MBBlocks.CORRUPTED_POLISHED_BLACKSTONE_BRICK_WALL.get());
      entry.accept(MBBlocks.SMOOTH_BLACKSTONE.get());
      entry.accept(MBBlocks.SMOOTH_BLACKSTONE_SLAB.get());
      entry.accept(MBBlocks.POLISHED_END_STONE.get());
      entry.accept(MBBlocks.POLISHED_END_STONE_STAIRS.get());
      entry.accept(MBBlocks.POLISHED_END_STONE_SLAB.get());
      entry.accept(MBBlocks.CHISELED_END_STONE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_END_STONE_BRICKS.get());
      entry.accept(MBBlocks.END_STONE_PILLAR.get());
      entry.accept(MBBlocks.END_STONE_TILES.get());
      entry.accept(MBBlocks.CRACKED_END_STONE_TILES.get());
      entry.accept(MBBlocks.END_STONE_TILE_STAIRS.get());
      entry.accept(MBBlocks.END_STONE_TILE_SLAB.get());
      entry.accept(MBBlocks.END_STONE_TILE_WALL.get());
      entry.accept(MBBlocks.MOSSY_END_STONE_BRICKS.get());
      entry.accept(MBBlocks.MOSSY_END_STONE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.MOSSY_END_STONE_BRICK_SLAB.get());
      entry.accept(MBBlocks.MOSSY_END_STONE_BRICK_WALL.get());
      entry.accept(MBBlocks.SMOOTH_END_STONE.get());
      entry.accept(MBBlocks.SMOOTH_END_STONE_SLAB.get());
      entry.accept(MBBlocks.POLISHED_PURPUR.get());
      entry.accept(MBBlocks.POLISHED_PURPUR_STAIRS.get());
      entry.accept(MBBlocks.POLISHED_PURPUR_SLAB.get());
      entry.accept(MBBlocks.CHISELED_PURPUR.get());
      entry.accept(MBBlocks.CRACKED_PURPUR_BLOCK.get());
      entry.accept(MBBlocks.PURPUR_TILES.get());
      entry.accept(MBBlocks.CRACKED_PURPUR_TILES.get());
      entry.accept(MBBlocks.PURPUR_TILE_STAIRS.get());
      entry.accept(MBBlocks.PURPUR_TILE_SLAB.get());
      entry.accept(MBBlocks.PURPUR_TILE_WALL.get());
      entry.accept(MBBlocks.MOSSY_PURPUR_BLOCK.get());
      entry.accept(MBBlocks.MOSSY_PURPUR_BLOCK_STAIRS.get());
      entry.accept(MBBlocks.MOSSY_PURPUR_BLOCK_SLAB.get());
      entry.accept(MBBlocks.MOSSY_PURPUR_BLOCK_WALL.get());
      entry.accept(MBBlocks.SMOOTH_PURPUR.get());
      entry.accept(MBBlocks.SMOOTH_PURPUR_SLAB.get());
      entry.accept(MBBlocks.COAL_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_COAL_BRICKS.get());
      entry.accept(MBBlocks.COAL_PILLAR.get());
      entry.accept(MBBlocks.CUT_COAL.get());
      entry.accept(MBBlocks.CRACKED_CUT_COAL.get());
      entry.accept(MBBlocks.IRON_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_IRON_BRICKS.get());
      entry.accept(MBBlocks.IRON_PILLAR.get());
      entry.accept(MBBlocks.CUT_IRON.get());
      entry.accept(MBBlocks.CRACKED_CUT_IRON.get());

      if (ctx.enabledFeatures().contains(FeatureFlags.UPDATE_1_21)) {
        entry.accept(MBBlocks.IRON_GRATE.get());
      }

      entry.accept(MBBlocks.GOLD_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_GOLD_BRICKS.get());
      entry.accept(MBBlocks.GOLD_PILLAR.get());
      entry.accept(MBBlocks.CUT_GOLD.get());
      entry.accept(MBBlocks.CRACKED_CUT_GOLD.get());
      entry.accept(MBBlocks.REDSTONE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_REDSTONE_BRICKS.get());
      entry.accept(MBBlocks.REDSTONE_PILLAR.get());
      entry.accept(MBBlocks.CUT_REDSTONE.get());
      entry.accept(MBBlocks.CRACKED_CUT_REDSTONE.get());
      entry.accept(MBBlocks.EMERALD_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_EMERALD_BRICKS.get());
      entry.accept(MBBlocks.EMERALD_PILLAR.get());
      entry.accept(MBBlocks.CUT_EMERALD.get());
      entry.accept(MBBlocks.CRACKED_CUT_EMERALD.get());
      entry.accept(MBBlocks.LAPIS_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_LAPIS_BRICKS.get());
      entry.accept(MBBlocks.LAPIS_PILLAR.get());
      entry.accept(MBBlocks.CUT_LAPIS.get());
      entry.accept(MBBlocks.CRACKED_CUT_LAPIS.get());
      entry.accept(MBBlocks.DIAMOND_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_DIAMOND_BRICKS.get());
      entry.accept(MBBlocks.DIAMOND_PILLAR.get());
      entry.accept(MBBlocks.CUT_DIAMOND.get());
      entry.accept(MBBlocks.CRACKED_CUT_DIAMOND.get());

      if (ctx.enabledFeatures().contains(FeatureFlags.UPDATE_1_21)) {
        entry.accept(MBBlocks.DIAMOND_GRATE.get());
      }

      entry.accept(MBBlocks.NETHERITE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_NETHERITE_BRICKS.get());
      entry.accept(MBBlocks.NETHERITE_PILLAR.get());
      entry.accept(MBBlocks.CUT_NETHERITE.get());
      entry.accept(MBBlocks.CRACKED_CUT_NETHERITE.get());

      if (ctx.enabledFeatures().contains(FeatureFlags.UPDATE_1_21)) {
        entry.accept(MBBlocks.NETHERITE_GRATE.get());
      }

      entry.accept(MBBlocks.CRACKED_QUARTZ_BRICKS.get());
      entry.accept(MBBlocks.CUT_QUARTZ.get());
      entry.accept(MBBlocks.CRACKED_CUT_QUARTZ.get());
      entry.accept(MBBlocks.AMETHYST_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_AMETHYST_BRICKS.get());
      entry.accept(MBBlocks.AMETHYST_PILLAR.get());
      entry.accept(MBBlocks.CUT_AMETHYST.get());
      entry.accept(MBBlocks.CRACKED_CUT_AMETHYST.get());

      /* COPPER BLOCKS */
      entry.accept(MBBlocks.COPPER_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.COPPER_PILLAR.get());
      entry.accept(MBBlocks.CRACKED_CUT_COPPER.get());
      entry.accept(MBBlocks.EXPOSED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.EXPOSED_CRACKED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.EXPOSED_COPPER_PILLAR.get());
      entry.accept(MBBlocks.EXPOSED_CRACKED_CUT_COPPER.get());
      entry.accept(MBBlocks.WEATHERED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.WEATHERED_CRACKED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.WEATHERED_COPPER_PILLAR.get());
      entry.accept(MBBlocks.WEATHERED_CRACKED_CUT_COPPER.get());
      entry.accept(MBBlocks.OXIDIZED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.OXIDIZED_CRACKED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.OXIDIZED_COPPER_PILLAR.get());
      entry.accept(MBBlocks.OXIDIZED_CRACKED_CUT_COPPER.get());
      entry.accept(MBBlocks.WAXED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.WAXED_CRACKED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.WAXED_COPPER_PILLAR.get());
      entry.accept(MBBlocks.WAXED_CRACKED_CUT_COPPER.get());
      entry.accept(MBBlocks.WAXED_EXPOSED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.WAXED_EXPOSED_CRACKED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.WAXED_EXPOSED_COPPER_PILLAR.get());
      entry.accept(MBBlocks.WAXED_EXPOSED_CRACKED_CUT_COPPER.get());
      entry.accept(MBBlocks.WAXED_WEATHERED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.WAXED_WEATHERED_CRACKED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.WAXED_WEATHERED_COPPER_PILLAR.get());
      entry.accept(MBBlocks.WAXED_WEATHERED_CRACKED_CUT_COPPER.get());
      entry.accept(MBBlocks.WAXED_OXIDIZED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.WAXED_OXIDIZED_CRACKED_COPPER_BRICKS.get());
      entry.accept(MBBlocks.WAXED_OXIDIZED_COPPER_PILLAR.get());
      entry.accept(MBBlocks.WAXED_OXIDIZED_CRACKED_CUT_COPPER.get());
      /* === */

      entry.accept(MBBlocks.BONE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_BONE_BRICKS.get());
      entry.accept(MBBlocks.BONE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.BONE_BRICK_SLAB.get());
      entry.accept(MBBlocks.BONE_BRICK_WALL.get());
      entry.accept(MBBlocks.BONE_TILES.get());
      entry.accept(MBBlocks.CRACKED_BONE_TILES.get());
      entry.accept(MBBlocks.BONE_TILE_STAIRS.get());
      entry.accept(MBBlocks.BONE_TILE_SLAB.get());
      entry.accept(MBBlocks.BONE_TILE_WALL.get());
      entry.accept(MBBlocks.SOUL_SANDSTONE.get());
      entry.accept(MBBlocks.SOUL_SANDSTONE_STAIRS.get());
      entry.accept(MBBlocks.SOUL_SANDSTONE_SLAB.get());
      entry.accept(MBBlocks.SOUL_SANDSTONE_WALL.get());
      entry.accept(MBBlocks.CHISELED_SOUL_SANDSTONE.get());
      entry.accept(MBBlocks.SOUL_SANDSTONE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_SOUL_SANDSTONE_BRICKS.get());
      entry.accept(MBBlocks.SOUL_SANDSTONE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.SOUL_SANDSTONE_BRICK_SLAB.get());
      entry.accept(MBBlocks.SOUL_SANDSTONE_BRICK_WALL.get());
      entry.accept(MBBlocks.SOUL_SANDSTONE_PILLAR.get());
      entry.accept(MBBlocks.SOUL_SANDSTONE_TILES.get());
      entry.accept(MBBlocks.CRACKED_SOUL_SANDSTONE_TILES.get());
      entry.accept(MBBlocks.SOUL_SANDSTONE_TILE_STAIRS.get());
      entry.accept(MBBlocks.SOUL_SANDSTONE_TILE_SLAB.get());
      entry.accept(MBBlocks.SOUL_SANDSTONE_TILE_WALL.get());
      entry.accept(MBBlocks.MOSSY_SOUL_SANDSTONE_BRICKS.get());
      entry.accept(MBBlocks.SMOOTH_SOUL_SANDSTONE.get());
      entry.accept(MBBlocks.SMOOTH_SOUL_SANDSTONE_SLAB.get());
      entry.accept(MBBlocks.SMOOTH_SOUL_SANDSTONE_STAIRS.get());
      entry.accept(MBBlocks.CUT_SOUL_SANDSTONE.get());
      entry.accept(MBBlocks.CUT_SOUL_SANDSTONE_SLAB.get());
      entry.accept(MBBlocks.PACKED_SNOW.get());
      entry.accept(MBBlocks.PACKED_SNOW_STAIRS.get());
      entry.accept(MBBlocks.PACKED_SNOW_SLAB.get());
      entry.accept(MBBlocks.POLISHED_SNOW.get());
      entry.accept(MBBlocks.POLISHED_SNOW_STAIRS.get());
      entry.accept(MBBlocks.POLISHED_SNOW_SLAB.get());
      entry.accept(MBBlocks.SNOW_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_SNOW_BRICKS.get());
      entry.accept(MBBlocks.SNOW_BRICK_STAIRS.get());
      entry.accept(MBBlocks.SNOW_BRICK_SLAB.get());
      entry.accept(MBBlocks.SNOW_BRICK_WALL.get());
      entry.accept(MBBlocks.SNOW_PILLAR.get());
      entry.accept(MBBlocks.SNOW_TILES.get());
      entry.accept(MBBlocks.CRACKED_SNOW_TILES.get());
      entry.accept(MBBlocks.SNOW_TILE_STAIRS.get());
      entry.accept(MBBlocks.SNOW_TILE_SLAB.get());
      entry.accept(MBBlocks.SNOW_TILE_WALL.get());
      entry.accept(MBBlocks.POLISHED_ICE.get());
      entry.accept(MBBlocks.POLISHED_ICE_STAIRS.get());
      entry.accept(MBBlocks.POLISHED_ICE_SLAB.get());
      entry.accept(MBBlocks.ICE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_ICE_BRICKS.get());
      entry.accept(MBBlocks.ICE_BRICK_STAIRS.get());
      entry.accept(MBBlocks.ICE_BRICK_SLAB.get());
      entry.accept(MBBlocks.ICE_BRICK_WALL.get());
      entry.accept(MBBlocks.ICE_PILLAR.get());
      entry.accept(MBBlocks.ICE_TILES.get());
      entry.accept(MBBlocks.CRACKED_ICE_TILES.get());
      entry.accept(MBBlocks.ICE_TILE_STAIRS.get());
      entry.accept(MBBlocks.ICE_TILE_SLAB.get());
      entry.accept(MBBlocks.ICE_TILE_WALL.get());
    }).build());

  private static final RegistryObject<CreativeModeTab> MORE_COLORED_BLOCKS = CREATIVE_MODE_TABS.register("more_colored_blocks", () -> CreativeModeTab.builder(CreativeModeTab.Row.TOP, 1)
    .icon(() -> MBBlocks.MAGENTA_SHINGLES.get().asItem().getDefaultInstance())
    .title(Component.translatable("itemGroup.somemoreblocks.coloredBlocks"))
    .displayItems((ctx, entry) -> {
      entry.accept(MBBlocks.TILED_GLASS.get());
      entry.accept(MBBlocks.TILED_TINTED_GLASS.get());
      entry.accept(MBBlocks.WHITE_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.LIGHT_GRAY_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.GRAY_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.BLACK_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.BROWN_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.RED_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.ORANGE_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.YELLOW_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.LIME_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.GREEN_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.CYAN_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.LIGHT_BLUE_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.BLUE_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.PURPLE_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.MAGENTA_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.PINK_STAINED_TILED_GLASS.get());
      entry.accept(MBBlocks.TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.WHITE_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.LIGHT_GRAY_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.GRAY_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.BLACK_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.BROWN_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.RED_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.ORANGE_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.YELLOW_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.LIME_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.GREEN_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.CYAN_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.LIGHT_BLUE_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.BLUE_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.PURPLE_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.MAGENTA_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.PINK_STAINED_TILED_GLASS_PANE.get());
      entry.accept(MBBlocks.SHINGLES.get());
      entry.accept(MBBlocks.WHITE_SHINGLES.get());
      entry.accept(MBBlocks.LIGHT_GRAY_SHINGLES.get());
      entry.accept(MBBlocks.GRAY_SHINGLES.get());
      entry.accept(MBBlocks.BLACK_SHINGLES.get());
      entry.accept(MBBlocks.BROWN_SHINGLES.get());
      entry.accept(MBBlocks.RED_SHINGLES.get());
      entry.accept(MBBlocks.ORANGE_SHINGLES.get());
      entry.accept(MBBlocks.YELLOW_SHINGLES.get());
      entry.accept(MBBlocks.LIME_SHINGLES.get());
      entry.accept(MBBlocks.GREEN_SHINGLES.get());
      entry.accept(MBBlocks.CYAN_SHINGLES.get());
      entry.accept(MBBlocks.LIGHT_BLUE_SHINGLES.get());
      entry.accept(MBBlocks.BLUE_SHINGLES.get());
      entry.accept(MBBlocks.PURPLE_SHINGLES.get());
      entry.accept(MBBlocks.MAGENTA_SHINGLES.get());
      entry.accept(MBBlocks.PINK_SHINGLES.get());
      entry.accept(MBBlocks.TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.WHITE_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.LIGHT_GRAY_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.GRAY_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.BLACK_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.BROWN_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.RED_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.ORANGE_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.YELLOW_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.LIME_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.GREEN_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.CYAN_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.LIGHT_BLUE_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.BLUE_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.PURPLE_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.MAGENTA_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.PINK_TERRACOTTA_BRICKS.get());
      entry.accept(MBBlocks.TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.WHITE_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.LIGHT_GRAY_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.GRAY_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.BLACK_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.BROWN_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.RED_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.ORANGE_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.YELLOW_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.LIME_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.GREEN_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.CYAN_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.LIGHT_BLUE_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.BLUE_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.PURPLE_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.MAGENTA_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.PINK_TERRACOTTA_TILES.get());
      entry.accept(MBBlocks.WHITE_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.LIGHT_GRAY_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.GRAY_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.BLACK_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.BROWN_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.RED_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.ORANGE_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.YELLOW_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.LIME_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.GREEN_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.CYAN_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.LIGHT_BLUE_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.BLUE_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.PURPLE_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.MAGENTA_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.PINK_CONCRETE_BRICKS.get());
      entry.accept(MBBlocks.WHITE_CONCRETE_TILES.get());
      entry.accept(MBBlocks.LIGHT_GRAY_CONCRETE_TILES.get());
      entry.accept(MBBlocks.GRAY_CONCRETE_TILES.get());
      entry.accept(MBBlocks.BLACK_CONCRETE_TILES.get());
      entry.accept(MBBlocks.BROWN_CONCRETE_TILES.get());
      entry.accept(MBBlocks.RED_CONCRETE_TILES.get());
      entry.accept(MBBlocks.ORANGE_CONCRETE_TILES.get());
      entry.accept(MBBlocks.YELLOW_CONCRETE_TILES.get());
      entry.accept(MBBlocks.LIME_CONCRETE_TILES.get());
      entry.accept(MBBlocks.GREEN_CONCRETE_TILES.get());
      entry.accept(MBBlocks.CYAN_CONCRETE_TILES.get());
      entry.accept(MBBlocks.LIGHT_BLUE_CONCRETE_TILES.get());
      entry.accept(MBBlocks.BLUE_CONCRETE_TILES.get());
      entry.accept(MBBlocks.PURPLE_CONCRETE_TILES.get());
      entry.accept(MBBlocks.MAGENTA_CONCRETE_TILES.get());
      entry.accept(MBBlocks.PINK_CONCRETE_TILES.get());
    }).build());

  private static final RegistryObject<CreativeModeTab> MORE_NATURAL_BLOCKS = CREATIVE_MODE_TABS.register("more_natural_blocks", () -> CreativeModeTab.builder(CreativeModeTab.Row.TOP, 2)
    .icon(() -> MBBlocks.TINY_CACTUS.get().asItem().getDefaultInstance())
    .title(Component.translatable("itemGroup.somemoreblocks.naturalBlocks"))
    .displayItems((ctx, entry) -> {
      entry.accept(MBBlocks.TINY_CACTUS.get());
      entry.accept(MBBlocks.DUNE_GRASS.get());
      entry.accept(MBBlocks.TALL_DUNE_GRASS.get());
      entry.accept(MBBlocks.SHORT_SNOW_GRASS.get());
      entry.accept(MBBlocks.TALL_SNOW_GRASS.get());
      entry.accept(MBBlocks.SNOW_FERN.get());
      entry.accept(MBBlocks.LARGE_SNOW_FERN.get());
      entry.accept(MBBlocks.CATTAIL.get());
      entry.accept(((LeavesBucketItem) MBItems.LEAVES_BUCKET.get()).getCreativeInventoryInstance());
      entry.accept(((LeavesBucketItem) MBItems.BIRCH_LEAVES_BUCKET.get()).getCreativeInventoryInstance());
      entry.accept(((LeavesBucketItem) MBItems.SPRUCE_LEAVES_BUCKET.get()).getCreativeInventoryInstance());
      entry.accept(((LeavesBucketItem) MBItems.AZALEA_LEAVES_BUCKET.get()).getCreativeInventoryInstance());
      entry.accept(((LeavesBucketItem) MBItems.FLOWERING_AZALEA_LEAVES_BUCKET.get()).getCreativeInventoryInstance());
      entry.accept(MBItems.SMALL_LILY_PADS.get());
      entry.accept(MBBlocks.LUMINOUS_FLOWER.get());

      if (ctx.hasPermissions()) {
        entry.accept(MBItems.BIG_LILY_PAD.get());
        entry.accept(MBItems.BROWN_MUSHROOM_COLONY.get());
        entry.accept(MBItems.TALL_BROWN_MUSHROOM_COLONY.get());
        entry.accept(MBItems.RED_MUSHROOM_COLONY.get());
        entry.accept(MBItems.TALL_RED_MUSHROOM_COLONY.get());
        entry.accept(MBItems.CRIMSON_FUNGUS_COLONY.get());
        entry.accept(MBItems.TALL_CRIMSON_FUNGUS_COLONY.get());
        entry.accept(MBItems.WARPED_FUNGUS_COLONY.get());
        entry.accept(MBItems.TALL_WARPED_FUNGUS_COLONY.get());
      }
    }).build());

  private static final RegistryObject<CreativeModeTab> MORE_REDSTONE_BLOCKS = CREATIVE_MODE_TABS.register("more_redstone_blocks", () -> CreativeModeTab.builder(CreativeModeTab.Row.TOP, 3)
    .icon(() -> MBBlocks.OCHRE_REDSTONE_FROGLIGHT.get().asItem().getDefaultInstance())
    .title(Component.translatable("itemGroup.somemoreblocks.redstoneBlocks"))
    .displayItems((ctx, entry) -> {
      entry.accept(MBBlocks.REDSTONE_BRICKS.get());
      entry.accept(MBBlocks.CRACKED_REDSTONE_BRICKS.get());
      entry.accept(MBBlocks.REDSTONE_PILLAR.get());
      entry.accept(MBBlocks.CUT_REDSTONE.get());
      entry.accept(MBBlocks.CRACKED_CUT_REDSTONE.get());
      entry.accept(MBBlocks.OCHRE_REDSTONE_FROGLIGHT.get());
      entry.accept(MBBlocks.VERDANT_REDSTONE_FROGLIGHT.get());
      entry.accept(MBBlocks.PEARLESCENT_REDSTONE_FROGLIGHT.get());
    }).build());

  public static void register(IEventBus event) {
    CREATIVE_MODE_TABS.register(event);
  }

  @SubscribeEvent
  public static void buildContents(BuildCreativeModeTabContentsEvent event) {
    if (event.getTabKey() == CreativeModeTabs.OP_BLOCKS && event.hasPermissions()) {
      event.accept(MBItems.BIG_LILY_PAD.get());
      event.accept(MBItems.BROWN_MUSHROOM_COLONY.get());
      event.accept(MBItems.TALL_BROWN_MUSHROOM_COLONY.get());
      event.accept(MBItems.RED_MUSHROOM_COLONY.get());
      event.accept(MBItems.TALL_RED_MUSHROOM_COLONY.get());
      event.accept(MBItems.CRIMSON_FUNGUS_COLONY.get());
      event.accept(MBItems.TALL_CRIMSON_FUNGUS_COLONY.get());
      event.accept(MBItems.WARPED_FUNGUS_COLONY.get());
      event.accept(MBItems.TALL_WARPED_FUNGUS_COLONY.get());
    }
  }
}
