name: Bug report
description: Something happened while I was playing with the mod that I believe is a issue.
title: "[Bug]: "
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |-
        Thank you for taking the time to report an issue, we are always trying to improve the mod and make your gameplay better!
        Please keep in mind that some issues may be more complex than they seem, so the timeframe for fixing the issue may and will be different.

        Minor issues may be delayed by major issues, but they will eventually be fixed!

  - type: dropdown
    id: bug_modloader
    attributes:
      label: ModLoader
      description: Which ModLoader is the issue occurring? (In any case, we will be investigating on both ModLoaders)
      multiple: false
      options:
        - Fabric
        - NeoForge
        - Minecraft Forge
        - All
      default: 3
    validations:
      required: true

  - type: input
    id: bug_version
    attributes:
      label: Mod version
      description: Which Mod version is the issue occurring? Keep in mind that this is the Mod version and NOT the game version!
      placeholder: "1.2.2"
    validations:
      required: true

  - type: textarea
    id: bug_descriptrion
    attributes:
      label: Description
      description: Important information about what the issue is and how it is causing it. If it is a Game Crash, please provide the Crash Report generated by the game!
      placeholder: A creeper blew up my game.
    validations:
      required: true

  - type: dropdown
    id: bug_priority
    attributes:
      label: Priority
      description: If you were to define a priority for this issue, what would it be?
      multiple: false
      options:
        - Low
        - Medium
        - High
        - Urgent
      default: 0
    validations:
      required: true
