modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"

license = "${license}"
issueTrackerURL = "${issues_tracker_url}"
showAsResourcePack = false

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL= "${main_url}"
logoFile = "assets/${mod_id}/icon_64.png"
credits = "Everyone who contributed on Crowdin and GitHub."
authors = "${mod_author}"
updateJSONURL = "${source_url}/raw/refs/heads/main/.github/neoforge-update.json"
description = '''
${description}
In loving memory of §dNicolle Gama§f.
'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"


#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange= " ${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"


[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
