plugins {
  id 'some-more-loaders'
  id "net.neoforged.moddev"
  id 'idea'
}

def common = project(":common")

neoForge {
  version = neoforge_version

  var File AT = common.file('src/main/resources/META-INF/accesstransformer.cfg')
  if (AT.exists()) {
    accessTransformers.from(AT.absolutePath)
  }

  runs {
    configureEach {
      systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
      ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
    }

    client {
      client()
      gameDirectory = this.mkdir(this.file("runs/client"))
    }

    server {
      server()
      gameDirectory = this.mkdir(this.file("runs/server"))
      programArgument '--nogui'
    }
  }

  mods {
    "${mod_id}" {
      sourceSet(sourceSets.main)
    }
  }
}

sourceSets.configureEach {
  def dir = layout.buildDirectory.dir("sourcesSets/${it.name}")
  it.java.destinationDirectory.set(dir)
  it.output.resourcesDir = dir.get().asFile
}

idea {
  module {
    downloadSources = true
    downloadJavadoc = true
    inheritOutputDirs = true
    outputDir = file("build/sourcesSets/main")
    testOutputDir = file("build/sourcesSets/test")
  }
}
